export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SCROLL_TO_BOTTOM_PAGE = 'SCROLL_TO_BOTTOM_PAGE';
export const SCROLL_TO_TOP_PAGE = 'SCROLL_TO_TOP_PAGE';

export const PROFILE_LOADED = 'PROFILE_LOADED';

export const LOGOUT = "LOGOUT";

export const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';
export const CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT';
export const CLEAR_CHAT_HISTORY = 'CLEAR_CHAT_HISTORY';
export const TOGGLE_MOBILE_CHAT = 'TOGGLE_MOBILE_CHAT';

export const VIEWER_COUNT_UPDATED = 'VIEWER_COUNT_UPDATED';

export const ROOM_JOINED = 'ROOM_JOINED';
export const ROOM_LEFT = 'ROOM_LEFT';
export const ROOM_CLOSED = 'ROOM_CLOSED'; 

export const ROOM_DATA_UPDATE = 'ROOM_DATA_UPDATE';