export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const PROFILE_LOADED = 'PROFILE_LOADED';

export const LOGOUT = "LOGOUT";

export const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';
export const CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT';
export const CLEAR_CHAT_HISTORY = 'CLEAR_CHAT_HISTORY';

export const VIEWER_COUNT_UPDATED = 'VIEWER_COUNT_UPDATED';

export const ROOM_JOINED = 'ROOM_JOINED';
export const ROOM_LEFT = 'ROOM_LEFT';